/* eslint-disable */
export var COUNTRIES = [
  {name:'India',code:'IN',dial:'+91',flag:'🇮🇳'},
  {name:'United Arab Emirates',code:'AE',dial:'+971',flag:'🇦🇪'},
  {name:'United States',code:'US',dial:'+1',flag:'🇺🇸'},
  {name:'United Kingdom',code:'GB',dial:'+44',flag:'🇬🇧'},
  {name:'Saudi Arabia',code:'SA',dial:'+966',flag:'🇸🇦'},
  {name:'Australia',code:'AU',dial:'+61',flag:'🇦🇺'},
  {name:'Canada',code:'CA',dial:'+1',flag:'🇨🇦'},
  {name:'Germany',code:'DE',dial:'+49',flag:'🇩🇪'},
  {name:'France',code:'FR',dial:'+33',flag:'🇫🇷'},
  {name:'Singapore',code:'SG',dial:'+65',flag:'🇸🇬'},
  {name:'Qatar',code:'QA',dial:'+974',flag:'🇶🇦'},
  {name:'Kuwait',code:'KW',dial:'+965',flag:'🇰🇼'},
  {name:'Oman',code:'OM',dial:'+968',flag:'🇴🇲'},
  {name:'Bahrain',code:'BH',dial:'+973',flag:'🇧🇭'},
  {name:'Pakistan',code:'PK',dial:'+92',flag:'🇵🇰'},
  {name:'Bangladesh',code:'BD',dial:'+880',flag:'🇧🇩'},
  {name:'Sri Lanka',code:'LK',dial:'+94',flag:'🇱🇰'},
  {name:'Nepal',code:'NP',dial:'+977',flag:'🇳🇵'},
  {name:'Philippines',code:'PH',dial:'+63',flag:'🇵🇭'},
  {name:'Malaysia',code:'MY',dial:'+60',flag:'🇲🇾'},
  {name:'Japan',code:'JP',dial:'+81',flag:'🇯🇵'},
  {name:'South Korea',code:'KR',dial:'+82',flag:'🇰🇷'},
];

export var INDIAN_STATES = {
  'Kerala':['Thiruvananthapuram','Kollam','Pathanamthitta','Alappuzha','Kottayam','Idukki','Ernakulam','Thrissur','Palakkad','Malappuram','Kozhikode','Wayanad','Kannur','Kasaragod'],
  'Tamil Nadu':['Chennai','Coimbatore','Madurai','Tiruchirappalli','Salem','Tirunelveli','Tiruppur','Vellore','Erode','Thoothukudi'],
  'Karnataka':['Bangalore Urban','Mysore','Mangalore','Belgaum','Hubli-Dharwad','Tumkur','Davanagere','Bellary','Bijapur','Shimoga'],
  'Andhra Pradesh':['Visakhapatnam','Vijayawada','Guntur','Nellore','Kurnool','Tirupati','Kakinada','Anantapur','Kadapa','Rajahmundry'],
  'Telangana':['Hyderabad','Warangal','Nizamabad','Karimnagar','Khammam','Mahbubnagar','Nalgonda','Adilabad','Rangareddy','Medak'],
  'Maharashtra':['Mumbai','Pune','Nagpur','Nashik','Aurangabad','Solapur','Thane','Kolhapur','Amravati','Sangli'],
  'Delhi':['New Delhi','North Delhi','South Delhi','East Delhi','West Delhi','Central Delhi','North East Delhi','North West Delhi','South East Delhi','South West Delhi'],
  'Gujarat':['Ahmedabad','Surat','Vadodara','Rajkot','Bhavnagar','Jamnagar','Junagadh','Gandhinagar','Anand','Bharuch'],
  'Rajasthan':['Jaipur','Jodhpur','Udaipur','Kota','Ajmer','Bikaner','Alwar','Bharatpur','Sikar','Pali'],
  'West Bengal':['Kolkata','Howrah','Durgapur','Asansol','Siliguri','Bardhaman','Malda','Baharampur','Habra','Jalpaiguri'],
  'Uttar Pradesh':['Lucknow','Kanpur','Ghaziabad','Agra','Varanasi','Meerut','Allahabad','Bareilly','Aligarh','Moradabad'],
  'Madhya Pradesh':['Bhopal','Indore','Jabalpur','Gwalior','Ujjain','Sagar','Dewas','Satna','Ratlam','Rewa'],
  'Punjab':['Ludhiana','Amritsar','Jalandhar','Patiala','Bathinda','Mohali','Hoshiarpur','Pathankot','Moga','Firozpur'],
  'Haryana':['Gurugram','Faridabad','Panipat','Ambala','Yamunanagar','Rohtak','Hisar','Karnal','Sonipat','Panchkula'],
  'Bihar':['Patna','Gaya','Bhagalpur','Muzaffarpur','Darbhanga','Purnia','Arrah','Begusarai','Katihar','Munger'],
  'Odisha':['Bhubaneswar','Cuttack','Rourkela','Berhampur','Sambalpur','Puri','Balasore','Bhadrak','Baripada','Jeypore'],
};
