-- ════════════════════════════════════════════════════════════════════
-- Frames v5 — clean green-screen art + 3 tidy categories.
--
-- The frames were regenerated by the user in the Gemini app on a FLAT solid
-- green background (incl. the centre hole), then green-keyed + size-normalised
-- to transparent 512px PNGs in public/frames/ (every frame's ring-hole is the
-- same diameter, so the avatar fits all identically). Dark/onyx frames now key
-- perfectly (dark != green) — the old checkerboard-bg problem is gone.
--
-- THREE categories only, in this display order:
--   1. Neon Wings   (199)  — 7 bright neon winged frames
--   2. VIP Wings    (299)  — 5 premium gold / onyx / bronze frames
--   3. Classic Rings(149)  — 6 plain glowing CSS rings (the kept "simple neon")
--
-- Sort bands are non-overlapping so section ORDER is deterministic
-- (Neon 110-170 < VIP 210-250 < Classic 310-360).
-- Requires 0049/0050/0051 (catalog_items). Re-run safe (idempotent upsert).
-- NOTE: bump FRAME_ASSET_V in src/utils/cosmetics.js when art changes (done: v5).
-- ════════════════════════════════════════════════════════════════════

-- 1. Retire frame_neon_cyan (no clean cyan art this round; replaced by Orchid).
update public.catalog_items set active = false where id = 'frame_neon_cyan';

-- 2. NEON WINGS (199) — 7 frames. (pink/magenta/violet/teal/aqua/blue art was
--    already replaced on disk; orchid is new.)
insert into public.catalog_items (id, kind, section, name, price_coins, is_premium, sort, payload, active) values
  ('frame_neon_pink',    'frame','Neon Wings','Pink Seraph',   199,false,110,'{"img":"/frames/frame_neon_pink.png"}',    true),
  ('frame_neon_magenta', 'frame','Neon Wings','Magenta Muse',  199,false,120,'{"img":"/frames/frame_neon_magenta.png"}', true),
  ('frame_neon_violet',  'frame','Neon Wings','Violet Crown',  199,false,130,'{"img":"/frames/frame_neon_violet.png"}',  true),
  ('frame_neon_orchid',  'frame','Neon Wings','Orchid Shade',  199,false,140,'{"img":"/frames/frame_neon_orchid.png"}',  true),
  ('frame_neon_teal',    'frame','Neon Wings','Teal Majesty',  199,false,150,'{"img":"/frames/frame_neon_teal.png"}',    true),
  ('frame_neon_aqua',    'frame','Neon Wings','Aqua Flutter',  199,false,160,'{"img":"/frames/frame_neon_aqua.png"}',    true),
  ('frame_neon_blue',    'frame','Neon Wings','Electric Blue', 199,false,170,'{"img":"/frames/frame_neon_blue.png"}',    true),
-- 3. VIP WINGS (299) — 5 frames. (gold/onyx art replaced; shadow/bronze/halo new.)
  ('frame_vip_gold',     'frame','VIP Wings','Golden Royale',  299,true, 210,'{"img":"/frames/frame_vip_gold.png"}',     true),
  ('frame_vip_onyx',     'frame','VIP Wings','Onyx Majesty',   299,true, 220,'{"img":"/frames/frame_vip_onyx.png"}',     true),
  ('frame_vip_shadow',   'frame','VIP Wings','Shadow Wings',   299,true, 230,'{"img":"/frames/frame_vip_shadow.png"}',   true),
  ('frame_vip_bronze',   'frame','VIP Wings','Bronze Empress', 299,true, 240,'{"img":"/frames/frame_vip_bronze.png"}',   true),
  ('frame_vip_halo',     'frame','VIP Wings','Royal Halo',     299,true, 250,'{"img":"/frames/frame_vip_halo.png"}',     true)
on conflict (id) do update set
  kind=excluded.kind, section=excluded.section, name=excluded.name, price_coins=excluded.price_coins,
  is_premium=excluded.is_premium, sort=excluded.sort, payload=excluded.payload, active=true;

-- 4. CLASSIC RINGS (149) — keep the 6 plain CSS rings; push them to the bottom.
update public.catalog_items set active = true, section = 'Classic Rings', price_coins = 149,
  sort = case id
    when 'frame_pulse' then 310 when 'frame_cyber' then 320 when 'frame_pinkhalo' then 330
    when 'frame_limewire' then 340 when 'frame_goldaura' then 350 when 'frame_aurora' then 360 end
 where id in ('frame_pulse','frame_cyber','frame_pinkhalo','frame_limewire','frame_goldaura','frame_aurora');
